<?php
$this->headScript()->offsetSetFile(97, $this->basePath() . '/public/js/jquery.validate.min.js');
?>

<style>
    tfoot tr th select{color:#000;}
</style>
<section class="menu-section">   
    <div class="container">  
        <div class="row">       
            <div class="col-md-12">    
                <div class="navbar-collapse collapse ">  
                    <ul id="menu-top" class="nav navbar-nav navbar-right">   
                        <li class="menu-top-active"><a href="<?php echo $this->url("application"); ?>"><?php echo $this->translate("Clients"); ?></a></li>           
                        <li><a href="<?php echo $this->url("statistics"); ?>"><?php echo $this->translate("Statistics"); ?></a></li>   
                        <li><a href="<?php echo $this->url("deal"); ?>"><?php echo $this->translate("Deals"); ?></a></li>   
                        <li><a href="<?php echo $this->url("loanadmin"); ?>"><?php echo $this->translate("Loan"); ?></a></li>   						
                    </ul>            
                </div>     
            </div>      
        </div> 
    </div>
</section>
<div class="content-wrapper">
    <div class="container">
        <div class="row">
            <div class="col-md-12">
                <h4 class="page-head-line"><?php echo $this->translate("Clients"); ?></h4>
            </div>
        </div>
        <div class="row">
            <div class="col-md-12 col-lg-12">
                <div class="row">
                    <div class="col-md-12">
                        <a href="<?php echo $this->url("client"); ?>"><input type="button" class="btn print-but clear" name="clear" value="<?php echo $this->translate('New Client'); ?>" /></a>
                    </div>
                </div>
                <div class="table-responsive table-box">

                    <table id="example" class="table table-striped table-bordered table-hover" cellspacing="0" width="100%">      
                        <thead>     
                            <tr>     
                                <!--<th></th> -->
                                <th><?php echo $this->translate("Password"); ?></th>								
                                <th class="select-filter"><?php echo $this->translate("Email"); ?></th>
                                <th class="select-filter"><?php echo $this->translate("Contact Name"); ?></th>
                                <th class="select-filter"><?php echo $this->translate("Address"); ?></th>
                                <th class="select-filter"><?php echo $this->translate("Phone"); ?></th>
                                <th class="select-filter"><?php echo $this->translate("ID/LLC"); ?></th>
                                <th class="select-filter"><?php echo $this->translate("Office Name"); ?></th>
                                <th class="select-filter"><?php echo $this->translate("#"); ?></th>
                            </tr>           
                        </thead>  
                        <tfoot style="display:table-header-group;">
                            <tr>
                                <td></td>							
                                <td><?php echo $this->translate("Email"); ?></td>
                                <td><?php echo $this->translate("Contact Name"); ?></td>
                                <td><?php echo $this->translate("Address"); ?></td>
                                <td><?php echo $this->translate("Phone"); ?></td>
                                <td><?php echo $this->translate("ID/LLC"); ?></td>
                                <td><?php echo $this->translate("Office Name"); ?></td>
                                <td><?php echo $this->translate("#"); ?></td>
                            </tr>
                        </tfoot>						
                        <tbody> 
                            <?php if (!empty($clientData)): ?>
                                <?php foreach ($clientData as $client): ?>
                                    <tr>
                                        <td><a href="<?php echo $this->url("client") ?>?id=<?php echo $client['user_id'] ?>"><?php echo $this->translate("Change"); ?></a></td>									
                                        <td><?php echo $client['user_email']; ?></td>
                                        <td><?php echo $client['user_contact_name']; ?></td>
                                        <td><?php echo $client['user_address']; ?></td>
                                        <td><?php echo $client['user_phone']; ?></td>
                                        <td><?php echo $client['user_id_LLC']; ?></td>
                                        <td><?php echo $client['user_office_name']; ?></td>
                                        <td><?php echo $client['user_id']; ?></td>
                                    </tr>
                                <?php endforeach; ?>
                            <?php endif; ?>
                        </tbody>           
                    </table>     
                </div>
            </div>
        </div>
    </div>
</div>
<script>
    $(document).ready(function() {
        $('#example').DataTable({
            initComplete: function() {
                this.api().columns('.select-filter').every(function() {
                    var column = this;

                    var select = $('<select><option value=""></option></select>')
                            .appendTo($(column.footer()).empty())
                            .on('change', function() {
                                var val = $.fn.dataTable.util.escapeRegex(
                                        $(this).val()
                                        );

                                column
                                        .search(val ? '^' + val + '$' : '', true, false)
                                        .draw();
                            });

                    column.data().unique().sort().each(function(d, j) {

                        select.append('<option value="' + d + '">' + d + '</option>')


                    });
                });
            },
            "language": {
                "lengthMenu": "<?php echo $this->translate("Display"); ?> _MENU_ <?php echo $this->translate("entries"); ?>",
                                "zeroRecords": "<?php echo $this->translate("No data found"); ?>",
                                "info": "<?php echo $this->translate("Showing page"); ?> _PAGE_ of _PAGES_",
                                "infoFiltered": "(<?php echo $this->translate("filtered from"); ?> _MAX_ <?php echo $this->translate("total records"); ?>)",
                                "paginate": {
                                    "previous": "<?php echo $this->translate("Previous"); ?>",
                                    "next": "<?php echo $this->translate("Next"); ?>"
                                }
                            }
                        });

                        jQuery("#deal_type").on("change", function() {
                            jQuery("#history_form").submit();
                        });
                    });
</script>
