<?php echo $this->doctype(); ?>
<html lang="en">
    <head>
        <meta charset="utf-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1" />
        <meta name="description" content="" />
        <meta name="author" content="" />
        <?php echo $this->headTitle('Info Share')->setSeparator(' - ')->setAutoEscape(false) ?>

        <?php
        echo $this->headMeta()
                ->appendName('viewport', 'width=device-width, initial-scale=1.0')
                ->appendHttpEquiv('X-UA-Compatible', 'IE=edge')
        ?>

        <?php
        echo $this->headLink(array('rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/public/img/favicon.ico'))
                ->prependStylesheet($this->basePath() . '/public/frontend/css/font-awesome.css')
                ->prependStylesheet($this->basePath() . '/public/frontend/css/style.css')
                ->prependStylesheet($this->basePath() . '/public/frontend/css/bootstrap.css')
        ?>
        <?php
        echo $this->headScript()
                ->prependFile($this->basePath() . '/public/frontend/js/bootstrap.js')
                ->prependFile($this->basePath() . '/public/frontend/js/jquery-1.11.1.js')
        ;
        ?>
        <!-- Scripts -->


    </head>
    <body>
        <?php include('messages.phtml'); ?>
        <?php echo $this->content; ?>
        <?php echo $this->inlineScript() ?>

    </body>

</html>
