<section class="menu-section">
    <div class="container">
        <div class="row">
            <div class="col-md-12">
                <div class="navbar-collapse collapse ">
                    <ul id="menu-top" class="nav navbar-nav navbar-right">
                        <?php /*<li class="menu-top-active"><a href="<?php echo $this->url(); ?>"><?php echo $this->translate("Main"); ?></a></li>*/?>
                        <li><a href="<?php echo $this->url("loan"); ?>"><?php echo $this->translate("Loan"); ?></a></li>
                        <li><a href="#"><?php echo $this->translate("Discounting"); ?></a></li>
                        <li><a href="#"><?php echo $this->translate("Search Data"); ?></a></li>
                        <li><a href="#"><?php echo $this->translate("Support"); ?></a></li>
                        <li><a href="#"><?php echo $this->translate("Reporting"); ?></a></li>
                        <li><a href="#"><?php echo $this->translate("History"); ?></a></li>
                    </ul>
                </div>
            </div>

        </div>
    </div>
</section>

<script>
//    jQuery(document).ready(function () {
//        jQuery('li').click(function () {
//            jQuery("li.menu-top-active").removeClass("menu-top-active");
//            jQuery(this).addClass('menu-top-active');
//        });
//    });

</script>

<!-- MENU SECTION END-->