<section class="menu-section"> 
    <div class="container">  
        <div class="row">   
            <div class="col-md-12"> 
                <div class="navbar-collapse collapse ">   
                    <ul id="menu-top" class="nav navbar-nav navbar-right">   
                        <?php /* <li class="menu-top-active"><a href="<?php echo $this->url(); ?>"><?php echo $this->translate("Main"); ?></a></li> */ ?>    
                        <li><a href="<?php echo $this->url("loan"); ?>"><?php echo $this->translate("Loan"); ?></a></li> 
                        <li><a href="<?php echo $this->url("discounting"); ?>"><?php echo $this->translate("Discounting"); ?></a></li>            
                        <li><a href="<?php echo $this->url("search"); ?>"><?php echo $this->translate("Search Data"); ?></a></li>   
                        <li><a href="<?php echo $this->url("support"); ?>"><?php echo $this->translate("Support"); ?></a></li>           
                        <li><a href="<?php echo $this->url("report"); ?>"><?php echo $this->translate("Reporting"); ?></a></li>     
                      <!-- <li><a href="<?php //echo $this->url("history"); ?>"><?php //echo $this->translate("History"); ?></a></li>-->  
                        <li><hr></li>
                        <li class="no-display"><a href="<?php echo $this->url("main"); ?>"><?php echo $this->translate("Dashboard"); ?></a></li>
                        <li class="no-display"><a href="<?php echo $this->url("loginfront", array("action" => "logout")) ?>"><?php echo $this->translate("Logout"); ?></a></li>
                    </ul>           
                </div>   
            </div>    
        </div>  
    </div>
</section>
<div class="clearfix"></div>
<div class="user-name-active">
    <div class="container"> 
        <h3><i class="fa fa-user user-icon" aria-hidden="true"></i><?php echo $this->translate("Welcome"); ?> <?php echo $userData['user_fullname']; ?></h3>
    </div>
</div>

<div class="content-wrapper">
    <div class="container">
        <div class="row">	
            <div class="col-md-12">                
                <h4 class="page-head-line"><?php echo $this->translate("NBFI System"); ?></h4>            
            </div>  
        </div>		
        <div class="row">            
            <div class="col-md-12 col-sm-12 col-xs-12">                
                <div class="news-main-box bk-clr-two dashboard-div-wrapper">
                    <div class="news-box">
                        <h2>News-1</h2>
                        <p>Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.</p>
                    </div>

                    <div class="news-box">
                        <h2>News-2</h2>
                        <p>Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.</p>
                    </div>
                </div>
            </div>            
            <?php /* <div class="col-md-4 col-sm-3 col-xs-6">                
              <a href="<?php echo $this->url("discounting"); ?>">
              <div class="dashboard-div-wrapper bk-clr-two">
              <i  class="fa fa-venus dashboard-div-icon" ></i>
              <div class="progress progress-striped active">
              <div class="progress-bar progress-bar-danger" role="progressbar" aria-valuenow="70" aria-valuemin="0" aria-valuemax="100" style="width: 70%">
              </div>
              </div>
              <h5><?php echo $this->translate("DISCOUNTING"); ?></h5>
              </div>
              </a>
              </div>
              <div class="col-md-4 col-sm-3 col-xs-6">
              <a href="<?php echo $this->url("search"); ?>">
              <div class="dashboard-div-wrapper bk-clr-three">
              <i  class="fa fa-venus dashboard-div-icon" ></i>
              <div class="progress progress-striped active">
              <div class="progress-bar progress-bar-success" role="progressbar" aria-valuenow="40" aria-valuemin="0" aria-valuemax="100" style="width: 40%">
              </div>
              </div>
              <h5><?php echo $this->translate("SEARCH"); ?></h5>
              </div>
              </a>
              </div>
              <div class="col-md-4 col-sm-3 col-xs-6">
              <a href="<?php echo $this->url("support"); ?>">
              <div class="dashboard-div-wrapper bk-clr-three">
              <i  class="fa fa-venus dashboard-div-icon" ></i>
              <div class="progress progress-striped active">
              <div class="progress-bar progress-bar-success" role="progressbar" aria-valuenow="40" aria-valuemin="0" aria-valuemax="100" style="width: 40%">
              </div>
              </div>
              <h5><?php echo $this->translate("SUPPORT"); ?></h5>
              </div>
              </a>
              </div>
              <div class="col-md-4 col-sm-3 col-xs-6">
              <a href="<?php echo $this->url("report"); ?>">
              <div class="dashboard-div-wrapper bk-clr-one">
              <i  class="fa fa-venus dashboard-div-icon" ></i>
              <div class="progress progress-striped active">
              <div class="progress-bar progress-bar-warning" role="progressbar" aria-valuenow="80" aria-valuemin="0" aria-valuemax="100" style="width: 80%">
              </div>
              </div>
              <h5><?php echo $this->translate("REPORTING"); ?></h5>
              </div>
              </a>
              </div>

              <div class="col-md-4 col-sm-3 col-xs-6">
              <a href="<?php echo $this->url("history"); ?>">
              <div class="dashboard-div-wrapper bk-clr-two">
              <i  class="fa fa-venus dashboard-div-icon" ></i>
              <div class="progress progress-striped active">
              <div class="progress-bar progress-bar-danger" role="progressbar" aria-valuenow="70" aria-valuemin="0" aria-valuemax="100" style="width: 70%">
              </div>
              </div>
              <h5><?php echo $this->translate("HISTORY"); ?></h5>
              </div>
              </a>
              </div> */ ?>          

        </div>    
    </div>
</div>