<?php
$this->headScript()->offsetSetFile(97, $this->basePath() . '/public/js/jquery.validate.min.js');
?>
<section class="menu-section">   
    <div class="container">  
        <div class="row">       
            <div class="col-md-12">    
                <div class="navbar-collapse collapse ">  
                    <ul id="menu-top" class="nav navbar-nav navbar-right">  
                        <li><a href="<?php echo $this->url("search"); ?>"><?php echo $this->translate("Search Data"); ?></a></li>					
                        <li><a href="<?php echo $this->url("loan"); ?>"><?php echo $this->translate("Loan"); ?></a></li>      
                        <li><a href="<?php echo $this->url("discounting"); ?>"><?php echo $this->translate("Discounting"); ?></a></li>
                        <li ><a href="<?php echo $this->url("support"); ?>"><?php echo $this->translate("Support"); ?></a></li>         
                        <li class="menu-top-active"><a href="<?php echo $this->url("report"); ?>"><?php echo $this->translate("Reporting"); ?></a></li>  
                   <!--<li><a href="<?php //echo $this->url("history"); ?>"><?php //echo $this->translate("History"); ?></a></li>--> 
                       <hr class="no-display">
                       <li class="no-display"><a href="<?php echo $this->url("loginfront", array("action" => "logout")) ?>">Logout</a></li>    
                    </ul>            
                </div>     
            </div>      
        </div> 
    </div>
</section>
   
<div class="content-wrapper">
    <div class="container">
        <div class="row">
            <div class="col-md-12">
                <h4 class="page-head-line"><?php echo $this->translate("Reporting"); ?></h4>
            </div>
        </div>
        <div class="row">
            <div class="col-md-12 col-lg-12">
                <form class="loan_form" id="loan_form" action="<?php echo $this->url("report", array("action" => "reportpost")) ?>" method="post">   
                    <input type="hidden" name="deal_type" value="2" />  
                    <div class="form-group">
                        <div class="row">
                            <div class="col-md-4 col-lg-4 col-box-small">
                                <label><?php echo $this->translate("ID/LLC"); ?></label>
                                <input type="text" class="form-control candidate_id_LLC" name="candidate_id_LLC" value="<?php
                                if (isset($data[0]['candidate_LLC_number'])) {
                                    echo $data[0]['candidate_LLC_number'];
                                }
                                ?>" name="candidate_id_LLC" <?php
                                       if (isset($data[0]['candidate_LLC_number'])) {
                                           echo "readonly";
                                       }
                                       ?> />     
                            </div>	

                            <div class="col-md-8 col-lg-8 col-box-big">
                                <label><?php echo $this->translate("Name"); ?></label>
                                <input type="text" class="form-control candidate_name"  name="candidate_name" value="<?php
                                if (isset($data[0]['candidate_name'])) {
                                    echo $data[0]['candidate_name'];
                                }
                                ?>" <?php
                                       if (isset($data[0]['candidate_name'])) {
                                           echo "readonly";
                                       }
                                       ?>/>	
                                <label class="error_LLC" style="display: none"></label>      
                            </div>

                        </div>
                    </div>
                    <div class="form-group">
                        <div class="row">
                            <div class="col-md-4 col-lg-4 col-box-small">
                               <label>&nbsp;</label>
                                <select class="form-control deal_type" name="deal_type1">
                                  <!--  <option value="Loan"><?php //echo $this->translate("Loan"); ?></option>
                                    <option value="Discounting"><?php //echo $this->translate("Discounting"); ?></option>-->
									
									<?php foreach($dealtype as $val):
									   
									  if($val['deal_type_eng_name']!='Reporting'):
									?>
									       <option value="<?php echo $val['deal_type_id'];?>"><?php echo $this->translate($val['deal_type_eng_name']);?></option>
									<?php 
									 endif;
									endforeach;?>    
                                </select>
                            </div>	
                            
                            <div class="col-md-8 col-lg-8 col-box-big">
                              <label>&nbsp;</label>
                                <select class="form-control candidate_name" id="loan_cmt" name="deal_comments">
                                    <?php foreach ($loanData as $loan): ?>
                                        <option value="<?php echo $this->translate($loan['rprt_id']); ?>"><?php echo $this->translate($loan['rprt_comment']); ?></option>
                                    <?php endforeach; ?>
                                </select>    
                                <select class="form-control candidate_name" id="discount_cmt" name="deal_comments" style="display: none;">
                                    <?php foreach ($discountData as $discount): ?>
                                        <option value="<?php echo $discount['rprt_id']; ?>"><?php echo $discount['rprt_comment']; ?></option>
                                    <?php endforeach; ?>
                                </select>    
                            </div>

                        </div>
                    </div>

                    <?php if (empty($data)) : ?>
                        <div class="form-group">
                            <input type="submit" name="submit" class="btn submit-but loan_save" value="<?php echo $this->translate('SAVE'); ?>"> 
                            <input type="button" name="save" value="<?php echo $this->translate('Clear'); ?>" class="btn print-but clear" /> 
                        </div>
                    <?php endif; ?>
                    <?php if (!empty($data)) : ?>
                        <div class="form-group">       
                            <a href="<?php echo $this->url("history") ?>" class="btn submit-but"><?php echo $this->translate('BACK'); ?></a>
                        </div>     
                    <?php endif; ?>

                </form>
            </div>
        </div>
    </div>
</div>
<div id="myModal" class="modal fade">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
                <h4 class="modal-title"><?php echo $this->translate("Confirmation"); ?></h4>
            </div>
            <div class="modal-body">
                <p><?php echo $this->translate("Do you want to clear changes you made to document before closing?"); ?></p>
                <p class="text-warning"><small><?php echo $this->translate("If you don't save, your changes will be lost"); ?>.</small></p>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-default" id="clear_btnn" data-dismiss="modal"><?php echo $this->translate("YES"); ?></button>
                <button type="button" class="btn btn-primary" data-dismiss="modal"><?php echo $this->translate("NO"); ?></button>
            </div>
        </div>
    </div>
</div>
<?php $url = $this->url("loan", array("action" => "getName")); ?>
<script>
    jQuery(document).ready(function() {
        jQuery(".loan_save").click(function() {
            jQuery(".error_LLC").hide();
        });

        jQuery(".deal_type").change(function() {
            var val = this.value;
			
            if (val == "3") {			
                jQuery("#loan_cmt").hide();
                jQuery("#discount_cmt").show();
            } else if (val == "1") {			
                jQuery("#loan_cmt").show();
                jQuery("#discount_cmt").hide();
            }
        });


        jQuery('.clear').click(function() {
            jQuery("#myModal")
                    .modal({backdrop: 'static', keyboard: true, show: true})
                    .one('click', '#clear_btnn', function(e) {
                        jQuery('#loan_form')[0].reset();
                    });
        });
        jQuery("#loan_form").validate({
            rules: {
                candidate_id_LLC: "required",
            },
            messages: {
                candidate_id_LLC: "<?php  echo $this->translate('Please enter LLC Number'); ?>",  
            }
        });
        jQuery(".candidate_id_LLC").change(function() {
            var candidate_id_LLC = jQuery(".candidate_id_LLC").val();
            jQuery.ajax({
                type: "POST",
                url: "<?php echo $url; ?>",
                data: {"candidate_id_LLC": candidate_id_LLC},
                async: true,
                dataType: "json",
                success: function(dta) {
                    if (dta.message == "true") {
                        jQuery(".candidate_name").val(dta.name);
                        jQuery(".candidate_name").prop('readonly', true);
                        jQuery(".error_LLC").hide();
                    } else {
                        jQuery(".error_LLC").html(dta.message);
                        jQuery(".candidate_name").val(dta.name);
                        jQuery(".candidate_name").removeAttr("readonly");
                        jQuery(".error_LLC").show();
                    }
                },
            });
        });
    });
</script>