<!-- success,failure  and any type of messages display here -->
<section id="message" class="bill-board">
    <div class="container">
        <div class="row">
            <div class="col-md-12 col-sm-12">
                <div class="contact-box-old flashmessage wow fadeInLeft">
                    <?php
                    if ($this->flashMessenger()) {
                        echo '<div class="col-lg-12">';
                        // In any of your .phtml files:
                        $flash = $this->flashMessenger();
                        $flash->setMessageOpenFormat('<div%s>
     <button type="button" class="close" data-dismiss="alert" aria-hidden="true">
         &times;
     </button>
     <ul><li>')
                                ->setMessageSeparatorString('</li><li>')
                                ->setMessageCloseString('</li></ul></div>');

                        echo $flash->render('error', array('alert', 'alert-dismissible', 'alert-danger'));
                        echo $flash->render('info', array('alert', 'alert-dismissible', 'alert-info'));
                        echo $flash->render('default', array('alert', 'alert-dismissible', 'alert-warning'));
                        echo $flash->render('success', array('alert', 'alert-dismissible', 'alert-success'));
                        echo '</div>';
                    }
                    ?>

                </div>
            </div>
        </div>
    </div>
</section>
<!-- end here -->