<?php
$this->headScript()->offsetSetFile(97, $this->basePath() . '/public/js/jquery.validate.min.js');
?> 
<section class="menu-section">  
    <div class="container">  
        <div class="row">       
            <div class="col-md-12">    
                <div class="navbar-collapse collapse ">  
                    <ul id="menu-top" class="nav navbar-nav navbar-right">   
                        <li class="menu-top-active"><a href="<?php echo $this->url("search"); ?>"><?php echo $this->translate("Search Data"); ?></a></li>   
                        <li><a href="<?php echo $this->url("loan"); ?>"><?php echo $this->translate("Loan"); ?></a></li>      
                        <li><a href="<?php echo $this->url("discounting"); ?>"><?php echo $this->translate("Discounting"); ?></a></li> 
                        <li><a href="<?php echo $this->url("support"); ?>"><?php echo $this->translate("Support"); ?></a></li>         
                        <li><a href="<?php echo $this->url("report"); ?>"><?php echo $this->translate("Reporting"); ?></a></li>  
                                                <!--<li><a href="<?php //echo $this->url("history");             ?>"><?php //echo $this->translate("History");             ?></a></li>-->
                        <hr class="no-display">
                        <li class="no-display"><a href="<?php echo $this->url("loginfront", array("action" => "logout")) ?>">Logout</a></li>    
                    </ul>            
                </div>     
            </div>      
        </div> 
    </div> 
</section>
<div class="content-wrapper">
    <div class="container">        
        <div class="row">    
            <div class="col-md-12">       
                <h4 class="page-head-line"><?php echo $this->translate("Search"); ?></h4>    
            </div>  
        </div>       
        <div class="row">
            <div class="col-md-12 col-lg-12">
                <?php $search = isset($_GET['candidate_id_LLC']) ? $_GET['candidate_id_LLC'] : ""; ?>     
                <?php
                if (!empty($search)) {
                    $attr = " disabled";
                    $link_c = "pointer-events: none; cursor: default;";
                } else {
                    $attr = "";
                    $link_c = "";
                }
                ?>
                <form method="get" id="search_data" action="<?php echo $this->url("search"); ?>">  
                    <div class="form-group">                
                        <div class="row">           
                            <div class="col-md-7 col-lg-7 col-box-search">   
                                <label><?php echo $this->translate("ID/LLC"); ?></label>
                                <div class="search-box">
                                    <input type="text" class="form-control candidate_id_LLC" name="candidate_id_LLC" value="<?php echo $search; ?>" <?php echo $attr; ?> />
                                    <a href="javascript:void(0)" class="search-but search_form" style="<?php echo $link_c; ?>"><i class="fa fa-search" aria-hidden="true"></i></a>
                                </div>	
                            </div>      
                            <div class="col-md-5 col-lg-5">   
                                <div class="new-search-box">
                                    <input type="button" class="new_search" value="<?php echo $this->translate("New Search"); ?>"/>
                                </div>	
                            </div>      
                        </div>           
                        <hr>
                        <?php
                        if (!empty($search)) {
                            $class = "display:block";
                        } else {
                            $class = "display:none";
                        }
                        ?>
                        <div class="enable_search" style="<?php echo $class; ?>">
                            <div class="form-group">    

                                <div class="row"> 
                                    <div class="col-md-3 col-lg-3 col-box-big"> 
                                        <?php
                                        if (isset($_GET)) {
                                            $name = $amount[0]['candidate_name'];
                                            $amount = $amount[0]['total_amount'];
                                        } else {
                                            $name = "";
                                            $amount = "";
                                        }
                                        ?>
                                        <label><?php echo $this->translate("Name"); ?></label>                          
                                        <input type="text" class="form-control candidate_name" name="candidate_name" value="<?php echo $name; ?>"  readonly/>
                                    </div>  
                                    <?php
                                    if ($user_count == 0) {
                                        $user_count = "";
                                    }
                                    ?>
                                    <div class="col-md-3 col-lg-3 col-box-small search-dat-box">         
                                        <label><?php echo $this->translate("Search in last 30days"); ?> </label>   
                                        <input type="text" class="form-control deal_amount" name="deal_amount" value="<?php
                                        if ($thirtydayCount != '0') {
                                            echo $thirtydayCount;
                                        }
                                        ?>"  readonly />     
                                    </div> 
                                    <div class="col-md-3 col-lg-3 col-box-small search-dat-box">         
                                        <label><?php echo $this->translate("Search in last 7days"); ?> </label>   
                                        <input type="text" class="form-control deal_amount" name="deal_amount" value="<?php
                                        if ($sevendayCount != '0') {
                                            echo $sevendayCount;
                                        }
                                        ?>"  readonly />     
                                    </div> 								
                                    <div class="col-md-3 col-lg-3 col-box-small">         
                                        <label><?php echo $this->translate("# Offices"); ?> </label>   
                                        <input type="text" class="form-control deal_amount" name="deal_amount" value="<?php echo $user_count; ?>"  readonly />     
                                    </div> 
                                </div>        
                            </div>  

                            <div class="table-responsive table-box">
                                <table class="table table-striped table-bordered table-hover display" id="example">
                                    <thead>
                                        <tr>
                                            <th><?php echo $this->translate("Guarantor 2"); ?></th>										
                                            <th><?php echo $this->translate("Guarantor 1"); ?></th>										
                                            <th><?php echo $this->translate("Comments"); ?></th>        
                                            <th><?php echo $this->translate("Due Date"); ?> </th>        
                                            <th><?php echo $this->translate("Amount"); ?></th>                 
                                            <th><?php echo $this->translate("Inserted Date"); ?></th>   
                                            <th><?php echo $this->translate("LLC Number"); ?></th>              
                                            <th><?php echo $this->translate("Type"); ?></th>            
                                        </tr>
                                    </thead>
                                    <tbody>  

                                        <?php if (!empty($searchData)) { ?>
                                            <?php foreach ($searchData as $srch): ?> 
                                                <tr>											            
                                                    <td><?php
                                                        if (@$srch['deal_guarantor_2'] != ''): echo '(' . $srch['deal_guarantor_2'] . ')-';
                                                        else: echo '(None)-';
                                                        endif;
                                                        if (@$srch['deal_guarantor_2_name'] != ''): echo $srch['deal_guarantor_2_name'];
                                                        else: echo 'None';
                                                        endif;
                                                        ?>
                                                    </td>											 
                                                    <td><?php
                                                        if (@$srch['deal_guarantor_1'] != ''): echo '(' . $srch['deal_guarantor_1'] . ')-';
                                                        else: echo '(None)-';
                                                        endif;
                                                        if (@$srch['deal_guarantor_1_name'] != ''): echo $srch['deal_guarantor_1_name'];
                                                        else: echo 'None';
                                                        endif;
                                                        ?></td>
                                                    <td><?php echo $srch['deal_comments']; ?></td>        
                                                    <td><?php echo $srch['deal_due_date']; ?></td>     
                                                    <td><?php echo $srch['deal_amount']; ?></td>   
                                                    <td><?php echo $srch['deal_start_date']; ?></td> 
                                                    <td><?php echo $srch['candidate_LLC_number']; ?></td>  
                                                    <td><?php echo $this->translate($srch['deal_type_eng_name']); ?></td>     
                                                </tr>  
                                            <?php endforeach; ?>            
                                        <?php } ?>  
                                    </tbody>  
                                </table>
                            </div>  

                            <div class="form-group">
                                <div class="sub-head">
                                    <h2><?php echo $this->translate("Reporting Comments"); ?></h2>
                                </div>						  
                                <?php if (!empty($comment)) { ?>
                                    <div class="row"> 
                                        <div class="col-md-12 reporting-com-box">
                                            <?php
                                            $a[] = '';
                                            for ($i = 0; $i < count($comment); $i++):

                                                if (!in_array($comment[$i]['deal_createBy'], $a)):
                                                    $a[] = $comment[$i]['deal_createBy'];
                                                    ?>
                                                    <div class="comment-report"> 

                                                        <h4><?php echo $this->translate("Office reported"); ?> <?php //echo $comment[$i]['user_office_name'];            ?></h4>
                                                        <?php
                                                        for ($j = 0; $j < count($comment); $j++):
                                                            if ($comment[$i]['deal_createBy'] == $comment[$j]['deal_createBy']):
                                                                ?>
                                                                <span><?php echo $comment[$j]['deal_due_date']; ?></span>
                                                                <p><?php echo $comment[$j]['deal_comments'] ?></p>                        
                                                                </br>  
                                                                <?php
                                                            endif;

                                                        endfor;
                                                        ?>
                                                    </div> 
                                                    <hr class="com-bor">
                                                <?php endif; ?>

                                            <?php endfor; ?>

                                        </div>	
                                    </div>
                                <?php } else { ?>
                                    <div class="row"> 
                                        <div class="col-md-12 reporting-com-box">
                                            <div class="comment-report">
                                                <p style="text-align: right"> <?php echo $this->translate("No reporting comments yet.") ?></p>
                                            </div>
                                        </div>
                                    </div>
                                <?php } ?>

                            </div>             
                            <div class="form-group">     
                                <input type="button" class="btn submit-but clear" name="clear" value="<?php echo $this->translate('Clear'); ?>" />  
                                <a href="<?php echo $this->url("search", array("action" => "printData")) ?>?candidate_id_LLC=<?php echo $search; ?>" class="btn print-but"><i class="fa fa-print" aria-hidden="true"></i><?php echo $this->translate("Print"); ?></a>
                            </div>   

                        </div>   
                </form>   
            </div>   
        </div> 
    </div>
</div>
</div>
<div id="myModal" class="modal fade">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
                <h4 class="modal-title"><?php echo $this->translate("Confirmation"); ?></h4>
            </div>
            <div class="modal-body">
                <p><?php echo $this->translate("Do you want to clear changes you made to document before closing?"); ?></p>
                <p class="text-warning"><small><?php echo $this->translate("If you don't save, your changes will be lost"); ?>.</small></p>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-default" id="clear_btnn" data-dismiss="modal"><?php echo $this->translate("YES"); ?></button>
                <button type="button" class="btn btn-primary" data-dismiss="modal"><?php echo $this->translate("NO"); ?></button>
            </div>
        </div>
    </div>
</div>
<?php $url = $this->url("loan", array("action" => "getName")); ?>

<script>
    function validateQty(event) {
        var key = window.event ? event.keyCode : event.which;

        if (event.keyCode == 8 || event.keyCode == 46
                || event.keyCode == 47 || event.keyCode == 39) {
            return true;
        }
        else if (key < 47 || key > 57) {
            return false;
        }
        else
            return true;
    }
    jQuery(document).ready(function() {
        jQuery('#due_date').datepicker({
            format: "yyyy-mm-dd"
        });
        jQuery('#deal_start_date').datepicker({
            format: "yyyy-mm-dd"
        });


        jQuery(".search_form").click(function() {
            jQuery('#search_data').submit();
        });
        //jQuery('#example').DataTable();

        jQuery('#example').DataTable({
            "language": {
                "lengthMenu": "<?php echo $this->translate("Display"); ?> _MENU_ <?php echo $this->translate("entries"); ?>",
                                "zeroRecords": "<?php echo $this->translate("No data found"); ?>",
                                "info": "<?php echo $this->translate("Showing page"); ?> _PAGE_ of _PAGES_",
                                "infoFiltered": "(<?php echo $this->translate("filtered from"); ?> _MAX_ <?php echo $this->translate("total records"); ?>)",
                                "paginate": {
                                    "previous": "<?php echo $this->translate("Previous"); ?>",
                                    "next": "<?php echo $this->translate("Next"); ?>"
                                }

                            }


                        });

                        jQuery('.clear').click(function() {
                            jQuery("#myModal")
                                    .modal({backdrop: 'static', keyboard: true, show: true})
                                    .one('click', '#clear_btnn', function(e) {
                                        jQuery('#search_data')[0].reset();
                                    });
                        });
                        jQuery("#search_data").validate({
                            rules: {
                                candidate_id_LLC: "required",
                            },
                            messages: {
                                candidate_id_LLC: "<?php echo $this->translate('Please enter LLC Number'); ?>",
                            }
                        });
                        jQuery('.candidate_id_LLC').keypress(function(e) {
                            if (e.which == 13) {
                                jQuery('#search_data').submit();
                                return false;
                            }
                        });
                        jQuery('.candidate_name').keypress(function(e) {
                            if (e.which == 13) {
                                jQuery('#search_data').submit();
                                return false;
                            }
                        });
                        jQuery('.deal_amount').keypress(function(e) {
                            if (e.which == 13) {
                                jQuery('#search_data').submit();
                                return false;
                            }
                        });

                        jQuery(".new_search").click(function() {
                            jQuery(".candidate_id_LLC").prop('disabled', false);
                            jQuery(".search_form").removeAttr("style");
                            jQuery(".enable_search").hide();
                            jQuery(".candidate_id_LLC").val("");
                        });

                    });
</script>