<?php
$this->headScript()
        ->offsetSetFile(97, $this->basePath() . '/public/js/jquery.validate.min.js');
?>
<section class="menu-section">   
    <div class="container">   
        <div class="row">     
            <div class="col-md-12">      
                <div class="navbar-collapse collapse ">      
                    <ul id="menu-top" class="nav navbar-nav navbar-right">       
                        <li><a href="<?php echo $this->url("loan"); ?>"><?php echo $this->translate("Loan"); ?></a></li> 
                        <li><a href="<?php echo $this->url("discounting"); ?>"><?php echo $this->translate("Discounting"); ?></a></li>  
                        <li><a href="<?php echo $this->url("search"); ?>"><?php echo $this->translate("Search Data"); ?></a></li>
                        <li><a href="<?php echo $this->url("support"); ?>"><?php echo $this->translate("Support"); ?></a></li>        
                        <li><a href="<?php echo $this->url("report"); ?>"><?php echo $this->translate("Reporting"); ?></a></li>   
                        <li><a href="<?php echo $this->url("history"); ?>"><?php echo $this->translate("History"); ?></a></li>   
                    </ul>     
                </div>    
            </div>   
        </div> 
    </div>
</section>
<div class="content-wrapper">  
    <div class="container">   
        <div class="row">    
            <div class="col-md-12">
                <?php if (empty($data)) { ?>
                    <h4 class="page-head-line"><?php echo $this->translate("Delete User"); ?></h4>  
                <?php } else { ?>
                    <h4 class="page-head-line"><?php echo $this->translate("View User"); ?></h4>  
                <?php } ?>
            </div>  
        </div>    
        <div class="row">    
            <div class="col-md-12 col-lg-12">   
                <form class="user_form" id="user_form_del" action="<?php echo $this->url("user", array("action" => "deletepost")) ?>" method="post">   
                    <div class="form-group"> 
                        <div class="row">
                            <div class="col-md-12 col-lg-12 col-box-big">    
                                <label><?php echo $this->translate("Email"); ?></label>    
                                <input type="email" class="form-control"  name="user_email" />
                            </div>         
                        </div>           
                    </div>
                    <div class="form-group"> 
                        <div class="row">
                            <div class="col-md-2 col-lg-2 col-box-small">
                                <a href="#" class="btn submit-but" data-href="<?php echo $this->url("user", array("action" => "deletepost")); ?>" data-toggle="modal" data-target="#confirm-delete"><?php echo $this->translate('DELETE'); ?></a>
                            </div>
                            <div class="col-md-2 col-lg-1 col-box-small">
                                <a href="<?php echo $this->url("user"); ?>"><?php echo $this->translate("Add User") ?></a>
                            </div>     
                        </div>     
                    </div>
                </form>      
            </div>   
        </div>   
    </div>
</div>
<div class="modal fade" id="confirm-delete" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
                <h4 class="modal-title"><?php echo $this->translate("Confirmation"); ?></h4>

            </div>
            <div class="modal-body">
                <p><?php echo $this->translate("User will permanent delete are you sure ?"); ?></p>           
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-default" data-dismiss="modal"><?php echo $this->translate("NO"); ?></button>
                <a class="btn btn-danger btn-ok"><?php echo $this->translate("YES"); ?></a>
            </div>
        </div>
    </div>
</div>

<script>

    jQuery(document).ready(function () {
        jQuery('.btn-ok').click(function () {
            jQuery('#user_form_del').submit();
        });
    });
</script>