<?php
$this->headScript()->offsetSetFile(97, $this->basePath() . '/public/js/jquery.validate.min.js');
?>

<style>
    tfoot tr th select{color:#000;}
</style>
<section class="menu-section">   
    <div class="container">  
        <div class="row">       
            <div class="col-md-12">    
                <div class="navbar-collapse collapse ">  
                    <ul id="menu-top" class="nav navbar-nav navbar-right">   
                        <li><a href="<?php echo $this->url("home"); ?>"><?php echo $this->translate("Clients"); ?></a></li>           
                        <li><a href="<?php echo $this->url("statistics"); ?>"><?php echo $this->translate("Statistics"); ?></a></li>   
                        <li><a href="<?php echo $this->url("deal"); ?>"><?php echo $this->translate("Deals"); ?></a></li>                        
                        <li class="menu-top-active"><a href="<?php echo $this->url("loanadmin"); ?>"><?php echo $this->translate("Loan"); ?></a></li>						
                    </ul>            
                </div>     
            </div>      
        </div> 
    </div>
</section>
<div class="content-wrapper">
    <div class="container">
        <div class="row">
            <div class="col-md-12">
                <h4 class="page-head-line"><?php echo $this->translate("Loan"); ?></h4>
            </div>
        </div>
        <div class="row">
            <div class="col-md-12 col-lg-12">

                <div class="table-responsive table-box">

                    <table id="example" class="table table-striped table-bordered table-hover" cellspacing="0" width="100%">      
                        <thead>     
                            <tr>     
                                <!--<th></th> -->
                                <th><?php echo $this->translate("Update"); ?></th>	
                               	<th class="select-filter"><?php echo $this->translate("Status"); ?></th>							
                                <th class="select-filter"><?php echo $this->translate("Due date"); ?></th>
                                <th class="select-filter"><?php echo $this->translate("Start date"); ?></th>                                
                                <th class="select-filter"><?php echo $this->translate("Type"); ?></th>
                                <th class="select-filter"><?php echo $this->translate("Loan&nbsp;Amount"); ?></th>
                                <th class="select-filter"><?php echo $this->translate("LLC&nbsp;Number"); ?></th>
                                <th class="select-filter"><?php echo $this->translate("Candidate&nbsp;Name"); ?></th> 	
                                <th class="select-filter"><?php echo $this->translate("User&nbsp;Office&nbsp;Name"); ?></th>       								
                                <th class="select-filter"><?php echo $this->translate("#"); ?></th>
                            </tr>           
                        </thead>  

                        <tfoot style="display:table-header-group;">
                            <tr>
                                <td></td>	
                                <td><?php echo $this->translate("Status"); ?></td>
                                <td><?php echo $this->translate("Due date"); ?></td>
                                <td><?php echo $this->translate("Start date"); ?></td>
                                <td><?php echo $this->translate("Type"); ?></td>  								
                                <td><?php echo $this->translate("Loan amount"); ?></td>
                                <td><?php echo $this->translate("LLC number"); ?></td>
                                <td><?php echo $this->translate("Candidate name"); ?></td>
                                <td><?php echo $this->translate("User office name"); ?></td>                                
                                <td><?php echo $this->translate("#"); ?></td>
                            </tr>
                        </tfoot>						
                        <tbody> 
                            <?php if (!empty($laon_data)): ?>
                                <?php foreach ($laon_data as $val): ?>
                                    <tr>
                                        <td>									 
                                            <?php if ($val['loan_status'] == '0' || $val['loan_status'] == '2'): ?>
                                                <form action="<?php echo $this->url("loanadmin", array("action" => "getVal")); ?>" method="post">		
                                                    <input type="hidden" name="val" value="<?php echo $val['deal_id']; ?>"/>			  
                                                    <button class="btn btn-success btn-xs" style="background:green;border:none;"><span class="glyphicon glyphicon-ok"></span><?php echo $this->translate("Approv");?></button>			  
                                                </form>
                                            <?php elseif ($val['loan_status'] == '1'): ?>
                                                <form action="<?php echo $this->url("loanadmin", array("action" => "getVal")); ?>" method="post">		
                                                    <input type="hidden" name="val" value="<?php echo $val['deal_id']; ?>"/>			  
                                                    <button class="btn btn-danger btn-xs" style="background:red;border:none;"><span class="glyphicon glyphicon-remove"></span><?php echo $this->translate("Reject");?></button>			  
                                                </form>
                                            <?php endif; ?>							 
                                        </td>										  
                                        <td><?php
                                            if ($val['loan_status'] == '0') {
                                                echo $this->translate("Pending");
                                            } elseif ($val['loan_status'] == '1') {
                                                echo $this->translate("Approved");
                                            } else {
                                                echo $this->translate("Rejected");
                                            }
                                            ?></td>                                       
                                        <td><?php echo $val['deal_due_date']; ?></td>
                                        <td><?php echo $val['deal_start_date']; ?></td>
                                        <td><?php
                                            if ($val['deal_type'] == '1') {
                                                echo $this->translate("Loan");
                                            } else {
                                                echo $this->translate("Dicounting");
                                            }
                                            ?></td>
                                        <td><?php echo $val['deal_amount']; ?></td> 										
                                        <td><?php echo $val['candidate_LLC_number']; ?></td>
                                        <td><?php echo $val['candidate_name']; ?></td> 										
                                        <td><?php echo @$val['user_office_name']; ?></td>
                                        <td><?php echo $val['deal_id']; ?></td> 
                                    </tr>
                                <?php endforeach; ?>
                            <?php endif; ?>
                        </tbody>           
                    </table>     
                </div>
            </div>
        </div>
    </div>
</div>
<script>
    function getState(val) {
        alert(val);

        $.ajax({
            type: 'POST',
            url: '<?php echo $this->url("loanadmin", array("action" => "getName")); ?>',
            data: {"val": val},
        });
    }
    $(document).ready(function() {

        $('#example').DataTable({
            initComplete: function() {
                this.api().columns('.select-filter').every(function() {
                    var column = this;

                    var select = $('<select><option value=""></option></select>')
                            .appendTo($(column.footer()).empty())
                            .on('change', function() {
                                var val = $.fn.dataTable.util.escapeRegex(
                                        $(this).val()
                                        );

                                column
                                        .search(val ? '^' + val + '$' : '', true, false)
                                        .draw();
                            });

                    column.data().unique().sort().each(function(d, j) {

                        select.append('<option value="' + d + '">' + d + '</option>')


                    });
                });
            },
            "language": {
                "lengthMenu": "<?php echo $this->translate("Display"); ?> _MENU_ <?php echo $this->translate("entries"); ?>",
                                "zeroRecords": "<?php echo $this->translate("No data found"); ?>",
                                "info": "<?php echo $this->translate("Showing page"); ?> _PAGE_ of _PAGES_",
                                "infoFiltered": "(<?php echo $this->translate("filtered from"); ?> _MAX_ <?php echo $this->translate("total records"); ?>)"
                            }
                        });

                        jQuery("#deal_type").on("change", function() {
                            jQuery("#history_form").submit();
                        });
                    });
</script>
