<?php
$this->headScript()->offsetSetFile(97, $this->basePath() . '/public/js/jquery.validate.min.js');
?>
<section class="menu-section">   
    <div class="container">  
        <div class="row">       
            <div class="col-md-12">    
                <div class="navbar-collapse collapse ">  
                    <ul id="menu-top" class="nav navbar-nav navbar-right">
                        <li><a href="<?php echo $this->url("search"); ?>"><?php echo $this->translate("Search Data"); ?></a></li>    					
                        <li><a href="<?php echo $this->url("loan"); ?>"><?php echo $this->translate("Loan"); ?></a></li>      
                        <li><a href="<?php echo $this->url("discounting"); ?>"><?php echo $this->translate("Discounting"); ?></a></li> 
                        <li class="menu-top-active"><a href="<?php echo $this->url("support"); ?>"><?php echo $this->translate("Support"); ?></a></li>         
                        <li><a href="<?php echo $this->url("report"); ?>"><?php echo $this->translate("Reporting"); ?></a></li>  
                    <!--<li><a href="<?php //echo $this->url("history"); ?>"><?php //echo $this->translate("History"); ?></a></li>--> 
                    <hr class="no-display">
                       <li class="no-display"><a href="<?php echo $this->url("loginfront", array("action" => "logout")) ?>">Logout</a></li>    
                    </ul>            
                </div>     
            </div>      
        </div> 
    </div>
</section>
<div class="content-wrapper">
    <div class="container">
        <div class="row">
            <div class="col-md-12">
                <h4 class="page-head-line"><?php echo $this->translate("Support"); ?></h4>
            </div>
        </div>
        <div class="row">
            <div class="col-md-12 col-lg-12">
                <form method="post" action="<?php echo $this->url("support", array("action" => "send")) ?>" id="support_form">
                    <div class="form-group">
                        <div class="row">
                            <div class="col-md-6 col-lg-6 col-box-big pull-right">
                                <label><?php echo $this->translate("Subject"); ?></label>
                                <input type="text" class="form-control" name="subject"  />

                            </div>							
                        </div>
                    </div>

                    <div class="form-group">
                        <div class="row">
                            <div class="col-md-12 col-lg-12 col-box-com">
                                <label><?php echo $this->translate("Message"); ?></label>
                                <textarea class="form-control" rows="6" name="message" ></textarea>							
                            </div>							
                        </div>
                    </div>
                    <div class="form-group">
                        <input type="submit" name="save" value="<?php echo $this->translate('Send'); ?>" class="btn submit-but save_form" />&nbsp;&nbsp;
                        <input type="button" name="save" value="<?php echo $this->translate('Clear'); ?>" class="btn print-but clear" /> 
                    </div>
                </form>
            </div>
        </div>

    </div>


</div>
<div id="myModal" class="modal fade">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
                <h4 class="modal-title"><?php echo $this->translate("Confirmation"); ?></h4>
            </div>
            <div class="modal-body">
                <p><?php echo $this->translate("Do you want to clear changes you made to document before closing?"); ?></p>
                <p class="text-warning"><small><?php echo $this->translate("If you don't save, your changes will be lost"); ?>.</small></p>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-default" id="clear_btnn" data-dismiss="modal"><?php echo $this->translate("YES"); ?></button>
                <button type="button" class="btn btn-primary" data-dismiss="modal"><?php echo $this->translate("NO"); ?></button>
            </div>
        </div>
    </div>
</div>
<script>
    jQuery(document).ready(function () {
        jQuery("#support_form").validate({
            rules: {
                subject: "required",
                message: "required",
            },
            messages: {
                subject: "<?php echo $this->translate('Please enter subject');?>",
                message: "<?php echo $this->translate('Please enter message');?>",
            }
        });
        jQuery('.clear').click(function () {
            jQuery("#myModal")
                    .modal({backdrop: 'static', keyboard: true, show: true})
                    .one('click', '#clear_btnn', function (e) {
                        jQuery('#support_form')[0].reset();
                    });
        });
    });
</script>