<?php
$this->headScript()->offsetSetFile(97, $this->basePath() . '/public/js/jquery.validate.min.js');
?>
<section class="menu-section">   
    <div class="container">  
        <div class="row">       
            <div class="col-md-12">    
                <div class="navbar-collapse collapse ">  
                    <ul id="menu-top" class="nav navbar-nav navbar-right">   
					   <li><a href="<?php echo $this->url("search"); ?>"><?php echo $this->translate("Search Data"); ?></a></li>
                        <li><a href="<?php echo $this->url("loan"); ?>"><?php echo $this->translate("Loan"); ?></a></li>      
                        <li class="menu-top-active"><a href="<?php echo $this->url("discounting"); ?>"><?php echo $this->translate("Discounting"); ?></a></li>           
                        <li><a href="<?php echo $this->url("support"); ?>"><?php echo $this->translate("Support"); ?></a></li>         
                        <li><a href="<?php echo $this->url("report"); ?>"><?php echo $this->translate("Reporting"); ?></a></li>  
                       <!-- <li><a href="<?php //echo $this->url("history");   ?>"><?php //echo $this->translate("History");   ?></a></li>-->
                       <hr class="no-display">
                       <li class="no-display"><a href="<?php echo $this->url("loginfront", array("action" => "logout")) ?>">Logout</a></li>     
                    </ul>            
                </div>     
            </div>      
        </div> 
    </div>
</section>
<div class="content-wrapper">
    <div class="container">
        <div class="row">
            <div class="col-md-12">
                <?php if (empty($data)) { ?>
                    <h4 class="page-head-line"><?php echo $this->translate("New Check Discounting"); ?></h4>
                <?php } else { ?>
                    <h4 class="page-head-line"><?php echo $this->translate("View Check Discounting"); ?></h4>  
                <?php } ?>
            </div>
        </div>
        <div class="row">
            <div class="col-md-12 col-lg-12">
                <form method="post" action="<?php echo $this->url("discounting", array("action" => "discount")); ?>" id="discount_form">
                    <input type="hidden" name="deal_type" value="3" />  

                    <div class="form-group">
                        <div class="row">
                            <div class="col-md-4 col-lg-4 col-box-small">
                                <label><?php echo $this->translate("ID/LLC"); ?></label>
                                <input type="text" class="form-control candidate_id_LLC" name="candidate_id_LLC" value="<?php
                                if (isset($data[0]['candidate_LLC_number'])) {
                                    echo $data[0]['candidate_LLC_number'];
                                }
                                ?>" <?php
                                       if (!empty($data)) {
                                           echo "readonly";
                                       }
                                       ?>/>     
                            </div>
                            <div class="col-md-8 col-lg-8 col-box-big">
                                <label><?php echo $this->translate("Name"); ?></label>
                                <input type="text" class="form-control candidate_name"  name="candidate_name" value="<?php
                                if (isset($c_name)) {
                                    echo $c_name;
                                }
                                ?>" <?php
                                       if (!empty($data)) {
                                           echo "readonly";
                                       }
                                       ?> />	
                                <label class="error_LLC" style="display: none"></label>      
                            </div>							
                        </div>
                    </div>
                    <div class="sub-head">
                        <h2><?php echo $this->translate("Discounting"); ?></h2>
                    </div>
                    <?php if (empty($data)): ?>
                        <div class="add-icon" >
                            <span onClick="addMoreRows(this.form);"><i class="fa fa-plus" aria-hidden="true"></i></span>
                        </div>
                    <?php endif; ?>
                    <div class="table-responsive table-box">
                        <table id="example" class="table table-striped table-bordered table-hover extra_tbl" cellspacing="0" width="100%">
                            <thead>
                                <tr>
                                    <th>&nbsp;</th>
                                    <th><?php echo $this->translate("Comments"); ?></th>
                                    <th><?php echo $this->translate("Due Date"); ?></th>
                                    <th><?php echo $this->translate("Amount"); ?></th>
                                </tr>
                            </thead>
                            <tbody id="addedRows">
                                <?php if (!empty($data)): ?>
                                    <?php foreach ($data as $DATA) : ?>
                                        <tr>
                                            <td>&nbsp;</th>
                                            <td><?php echo $DATA['deal_comments'] ?></td>
                                            <td><?php echo $DATA['deal_due_date'] ?></td>
                                            <td><?php echo $DATA['deal_amount'] ?></td>
                                        </tr>
                                    <?php endforeach; ?>
                                <?php endif; ?>
                            </tbody>
                        </table>
                    </div>
                    <?php if (empty($data)): ?>
                        <div class="form-group">
                            <input type="submit" class="btn submit-but loan_save" value="<?php echo $this->translate('Save'); ?>"/>
                            <input type="button" class="btn print-but clear" name="clear" value="<?php echo $this->translate('Clear'); ?>" />  
                        </div>
                    <?php endif; ?>
                    <?php if (!empty($data)) : ?>
                        <div class="form-group">       
                            <a href="<?php echo $this->url("history") ?>" class="btn submit-but"><?php echo $this->translate('BACK'); ?></a>
                        </div>     
                    <?php endif; ?>
                </form>
            </div>
        </div>

    </div>

</div>
<div id="myModal" class="modal fade">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
                <h4 class="modal-title"><?php echo $this->translate("Confirmation"); ?></h4>
            </div>
            <div class="modal-body">
                <p><?php echo $this->translate("Do you want to clear changes you made to document before closing?"); ?></p>
                <p class="text-warning"><small><?php echo $this->translate("If you don't save, your changes will be lost"); ?>.</small></p>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-default" id="clear_btnn" data-dismiss="modal"><?php echo $this->translate("YES"); ?></button>
                <button type="button" class="btn btn-primary" data-dismiss="modal"><?php echo $this->translate("NO"); ?></button>
            </div>
        </div>
    </div>
</div>
<?php $url = $this->url("loan", array("action" => "getName")); ?>
<script>
    jQuery(document).ready(function() {
        jQuery('.clear').click(function() {
            jQuery("#myModal")
                    .modal({backdrop: 'static', keyboard: true, show: true})
                    .one('click', '#clear_btnn', function(e) {
                        jQuery('#discount_form')[0].reset();
                    });
        });
        jQuery('#example').DataTable({
            "language": {
                "lengthMenu": "<?php echo $this->translate("Display"); ?> _MENU_ <?php echo $this->translate("entries"); ?>",
                                "zeroRecords": "<?php echo $this->translate("No data found"); ?>",
                                "info": "<?php echo $this->translate("Showing page"); ?> _PAGE_ of _PAGES_",
                                "infoFiltered": "(<?php echo $this->translate("filtered from"); ?> _MAX_ <?php echo $this->translate("total records"); ?>)",
                                "paginate": {
                                    "previous": "<?php echo $this->translate("Previous"); ?>",
                                    "next": "<?php echo $this->translate("Next"); ?>"
                                }
                            }

                        });
                        jQuery.validator.addMethod("DateFormat", function(value, element) {
                            return value.match(/^(0[1-9]|[12][0-9]|3[01])[- //.](0[1-9]|1[012])[- //.](19|20)\d\d$/);
                        },
                                "<?php echo $this->translate('Please enter a date in the format dd/mm/yyyy');?>"
                                );
                        jQuery("#discount_form").validate({
                            rules: {
                                candidate_id_LLC: "required",
                            },
                            messages: {
                                candidate_id_LLC: "<?php echo $this->translate('Please enter LLC Number'); ?>",
                            }
                        });
                        jQuery(".loan_save").click(function() {
                            jQuery(".error_LLC").hide();
                        });
                        jQuery(".candidate_id_LLC").change(function() {
                            var candidate_id_LLC = jQuery(".candidate_id_LLC").val();
                            jQuery.ajax({
                                type: "POST",
                                url: "<?php echo $url; ?>",
                                data: {"candidate_id_LLC": candidate_id_LLC},
                                async: true,
                                dataType: "json",
                                success: function(dta) {
                                    if (dta.message == "true") {

                                        jQuery(".candidate_name").val(dta.name);
                                        jQuery(".candidate_name").prop('readonly', true);
                                        jQuery(".error_LLC").hide();
                                    } else {
                                        jQuery(".error_LLC").html(dta.message);
                                        jQuery(".candidate_name").val(dta.name);
                                        jQuery(".candidate_name").removeAttr("readonly");
                                        jQuery(".error_LLC").show();
                                    }
                                },
                            });
                        });
                    });
                    var rowCount = 0;
                    function addMoreRows(frm) {

                        var recRow = '<tr id="rowCount' + rowCount + '"><td class="center"><a href="javascript:void(0);" onclick="removeRow(' + rowCount + ');" > <i class="fa fa-trash delete-icon" aria-hidden="true"></i></a></td><td><input name="deal_comments[' + rowCount + ']" type="text" value =""/> </td><td><input name="deal_due_date[' + rowCount + ']" type="text" value ="" onkeypress="return validateQty(event);"  id="due_date_' + rowCount + '"  class="deal_due_date" /><input name="deal_start_date[' + rowCount + ']" type="hidden" value ="<?php echo date("d/m/Y"); ?>"  id="start_date_' + rowCount + '"  class="deal_start_date" /></td><td><input class="deal_amount_' + rowCount + '" name="deal_amount[' + rowCount + ']" type="number" onkeypress="return checkValue(event);" value =""/> </td> </tr>';
                        jQuery('#addedRows').append(recRow);
                        jQuery(".odd").remove();
//        jQuery('input[name="deal_comments[' + rowCount + ']"]').rules("add", {
//            required: true
//        });
                        jQuery('input[name="deal_due_date[' + rowCount + ']"]').rules("add", {
                            required: true,
                            DateFormat: true
                        });
                        jQuery('input[name="deal_amount[' + rowCount + ']"]').rules("add", {
                            required: true,
                            number: true
                        });
//                        var regExp = /[0-9\.\,]/;
//                        jQuery('.deal_amount_' + rowCount).on('keydown keyup', function (e) {
//                            var value = String.fromCharCode(e.which) || e.key;
//                            // Only numbers, dots and commas
//                            if (!regExp.test(value)
//                                    && e.which != 188 // ,
//                                    && e.which != 190 // .
//                                    && e.which != 8   // backspace
//                                    && e.which != 46  // delete
//                                    && (e.which < 37  // arrow keys
//                                            || e.which > 40)) {
//                                e.preventDefault();
//                                return false;
//                            }
//                        });
                        jQuery('#due_date_' + rowCount).datepicker({
                            format: "dd/mm/yyyy"
                        });
                        jQuery('.deal_amount_' + rowCount).focus();

                        rowCount++;
                    }

                    function removeRow(removeNum) {
                        jQuery('#rowCount' + removeNum).remove();
                    }
                    function validateQty(event) {
                        var key = window.event ? event.keyCode : event.which;

                        if (event.keyCode == 8 || event.keyCode == 46
                                || event.keyCode == 47 || event.keyCode == 39) {
                            return true;
                        }
                        else if (key < 47 || key > 57) {
                            return false;
                        }
                        else
                            return true;
                    }
                    function checkValue(event) {
                        var key = window.event ? event.keyCode : event.which;

                        if (event.keyCode == 8 || event.keyCode == 9 || event.keyCode == 44
                                || event.keyCode == 46 || event.keyCode == 39) {
                            return true;
                        }
                        else if (key < 44 || key > 57) {
                            return false;
                        }
                        else
                            return true;
                    }


</script>