<?php
$this->headScript()->offsetSetFile(97, $this->basePath() . '/public/js/jquery.validate.min.js');
?>
<section class="menu-section">   
    <div class="container">  
        <div class="row">       
            <div class="col-md-12">    
                <div class="navbar-collapse collapse ">  
                    <ul id="menu-top" class="nav navbar-nav navbar-right">   
                        <li><a href="<?php echo $this->url("loan"); ?>"><?php echo $this->translate("Loan"); ?></a></li>      
                        <li><a href="<?php echo $this->url("discounting"); ?>"><?php echo $this->translate("Discounting"); ?></a></li>           
                        <li><a href="<?php echo $this->url("search"); ?>"><?php echo $this->translate("Search Data"); ?></a></li>   
                        <li><a href="<?php echo $this->url("support"); ?>"><?php echo $this->translate("Support"); ?></a></li>         
                        <li><a href="<?php echo $this->url("report"); ?>"><?php echo $this->translate("Reporting"); ?></a></li>  
                      <!--<li class="menu-top-active"><a href="<?php //echo $this->url("history"); ?>"><?php //echo $this->translate("History"); ?></a></li>--> 
                       <hr class="no-display">
                       <li class="no-display"><a href="<?php echo $this->url("loginfront", array("action" => "logout")) ?>">Logout</a></li>    
                    </ul>            
                </div>     
            </div>      
        </div> 
    </div>
</section>
<div class="content-wrapper">
    <div class="container">
        <div class="row">
            <div class="col-md-12">
                <h4 class="page-head-line"><?php echo $this->translate("History"); ?></h4>
            </div>
        </div>
        <?php $deal_type = isset($_GET['deal_type']) ? $_GET['deal_type'] : ""; ?>

        <div class="row">
            <div class="col-md-12 col-lg-12">
                <form method="get" action="<?php echo $this->url("history"); ?>" id="history_form">  
                    <div class="form-group">
                        <div class="row">
                            <div class="col-md-4 col-lg-4 col-box-small pull-right">							
                                <label><?php echo $this->translate('Type');?></label>
                                <select class="selectpicker" id="deal_type" name="deal_type" title="Choose one of the following...">
								  <option value=""><?php echo $this->translate('All');?></option>
								<?php
								   foreach($dealtype as $val):
								?>
								  <option value="<?php echo $val['deal_type_id'];?>" <?php if ($deal_type == $val['deal_type_id']) { echo "selected";  } ?>><?php echo $this->translate($val['deal_type_eng_name']);?></option>
								  
								<?php
                                   endforeach;
                                ?>						
                                </select>
                            </div>
                        </div>
                    </div>
                    <hr>				
                    <div class="table-responsive table-box">

                        <table id="example" class="table table-striped table-bordered table-hover" cellspacing="0" width="100%">      
                            <thead>     
                                <tr>     
                                    <!--<th></th> -->
                                    <th><?php echo $this->translate("Create Date"); ?></th>
                                    <th><?php echo $this->translate("Amount"); ?></th>
                                    <th><?php echo $this->translate("Date"); ?></th>
                                    <th><?php echo $this->translate("ID/LLC"); ?></th>
                                    <th><?php echo $this->translate("Type"); ?></th>
                                </tr>           
                            </thead>                   
                            <tbody> 
                                <?php if (!empty($searchData)) { ?>
                                    <?php foreach ($searchData as $srch): ?> 
                                        <?php
                                        if ($srch['deal_type'] == "Loan") {
                                            $url = $this->url("loan");
                                        } else if ($srch['deal_type'] == "Reporting") {
                                            $url = $this->url("report");
                                        } else if ($srch['deal_type'] == "Discounting") {
                                            $url = $this->url("discounting");
                                        }
                                        ?>
                                        <tr>                           
                                            <?php /* <td><a href="<?php echo $url; ?>?deal_id=<?php echo $srch['deal_id'] ?>&candidate_id=<?php echo $srch['candidate_id'] ?>"><?php echo $this->translate("View"); ?></a></td> */ ?>
                                            <td><?php echo date("d/m/Y", strtotime($srch['deal_createDate'])); ?></td>        
                                            <td><?php echo $srch['deal_amount']; ?></td>        
                                            <td><?php echo $srch['deal_due_date']; ?></td>     
                                            <td><?php echo $srch['candidate_LLC_number']; ?></td>   
                                            <td><?php echo $this->translate($srch['deal_type_eng_name']); ?></td>     
                                        </tr>  
                                    <?php endforeach; ?>            
                                <?php } ?>  
                            </tbody>           
                        </table>     


                    </div>
                    <!--<div class="form-group">
                        <input type="reset" value="<?php //echo $this->translate('Clear');   ?>" name="clear" class="btn submit-but" />
                    </div>-->
                </form>
            </div>
        </div>
    </div>
</div>
<?php $url = $this->url("loan", array("action" => "getName")); ?>
<script>
    jQuery(document).ready(function () {
        jQuery('#example').DataTable({
            
			             "language": {
                "lengthMenu": "<?php echo $this->translate("Display"); ?> _MENU_ <?php echo $this->translate("entries"); ?>",
                                "zeroRecords": "<?php echo $this->translate("No data found"); ?>",
                                "info": "<?php echo $this->translate("Showing page"); ?> _PAGE_ of _PAGES_",
                                "infoFiltered": "(<?php echo $this->translate("filtered from"); ?> _MAX_ <?php echo $this->translate("total records"); ?>)"
                            }
			
                        });

                        jQuery("#deal_type").on("change", function () {
                            jQuery("#history_form").submit();
                        });


                    });
</script>