<?php
$this->headScript()->offsetSetFile(97, $this->basePath() . '/public/js/jquery.validate.min.js');
?>
<section class="menu-section">   
    <div class="container">  
        <div class="row">       
            <div class="col-md-12">    
                <div class="navbar-collapse collapse ">  
                    <ul id="menu-top" class="nav navbar-nav navbar-right">   
                        <li><a href="<?php echo $this->url("home"); ?>"><?php echo $this->translate("Clients"); ?></a></li>           
                        <li><a href="<?php echo $this->url("statistics"); ?>"><?php echo $this->translate("Statistics"); ?></a></li>   
                        <li class="menu-top-active"><a href="<?php echo $this->url("deal"); ?>"><?php echo $this->translate("Deals"); ?></a></li>
                        <li><a href="<?php echo $this->url("loanadmin"); ?>"><?php echo $this->translate("Loan"); ?></a></li> 						
                    </ul>            
                </div>     
            </div>      
        </div> 
    </div>
</section>
<div class="content-wrapper">
    <div class="container">
        <div class="row">
            <div class="col-md-12">
                <h4 class="page-head-line"><?php echo $this->translate("Deals"); ?></h4>
            </div>
        </div>
        <div class="row">
            <div class="col-md-12 col-lg-12">
                <form method="get" action="<?php echo $this->url('deal'); ?>">
                    <?php
                    $show_from = isset($_GET['show_from']) ? $_GET['show_from'] : "";
                    $show_to = isset($_GET['show_to']) ? $_GET['show_to'] : "";
                    ?>

                    <div class="row">
                        <div class = "col-md-4 col-lg-4 col-box-small">
                            <label><?php echo $this->translate("From"); ?></label>  
                            <input type="text" class="form-control show_from" id="show_from" onkeypress='return validateQty(event);' name="show_from" value="<?php
                            if ($show_from == "") {
                                echo date("d/m/Y");
                            } else {
                                echo $show_from;
                            }
                            ?>" />
                        </div>
                        <div class="col-md-4 col-lg-4 col-box-small">
                            <label><?php echo $this->translate("To"); ?></label>  
                            <input type="text" class="form-control show_to" id="show_to" onkeypress='return validateQty(event);' name="show_to" value="<?php
                            if ($show_to == "") {
                                echo date("d/m/Y");
                            } else {
                                echo $show_to;
                            }
                            ?>" />
                        </div>

                        <div class="col-md-4 col-lg-4 col-box-small">
                            <input type="submit" class="btn print-but clear" name="clear" value="<?php echo $this->translate('Show'); ?>" />
                        </div>

                    </div>
                </form>
                <div class="table-responsive table-box">

                    <table id="example" class="table table-striped table-bordered table-hover" cellspacing="0" width="100%">      
                        <thead>     
                            <tr>     
                                <th><?php echo $this->translate("End Date"); ?></th>
                                <th><?php echo $this->translate("Start Date"); ?></th>
                                <th><?php echo $this->translate("Status"); ?></th>
                                <th><?php echo $this->translate("Type"); ?></th>
                                <th><?php echo $this->translate("Phone"); ?></th>
                                <th><?php echo $this->translate("Name"); ?></th>
                                <th><?php echo $this->translate("Id"); ?></th>
                                <th><?php echo $this->translate("Office"); ?></th>
                                <th><?php echo $this->translate("#"); ?></th>
                            </tr>           
                        </thead> 
                        <tfoot style="display:table-header-group;">
                            <tr>
                                <td><?php echo $this->translate("End Date"); ?></td>							
                                <td><?php echo $this->translate("Start Date"); ?></td>
                                <td><?php echo $this->translate("Status"); ?></td>
                                <td><?php echo $this->translate("Type"); ?></td>
                                <td><?php echo $this->translate("Phone"); ?></td>
                                <td><?php echo $this->translate("Name"); ?></td>
                                <td><?php echo $this->translate("Id"); ?></td>
                                <td><?php echo $this->translate("Office"); ?></td>
                                <td><?php echo $this->translate("#"); ?></td>
                            </tr>
                        </tfoot>	
                        <?php if (!empty($clientData)): ?>
                            <?php foreach ($clientData as $client): ?>
                                <tr>
                                    <td><?php echo $client['deal_due_date']; ?></td>
                                    <td><?php echo $client['deal_start_date']; ?></td>
                                    <td></td>
                                    <td><?php echo $this->translate($client['deal_type_eng_name']); ?></td>
                                    <td><?php echo $client['deal_phone']; ?></td>
                                    <td><?php echo $client['candidate_name']; ?></td>
                                    <td><?php echo $client['candidate_LLC_number']; ?></td>
                                    <td><?php echo $client['office_name']; ?></td>
                                    <td><?php echo $client['deal_id']; ?></td>
                                </tr>
                            <?php endforeach; ?>
                        <?php endif; ?>
                        <tbody> 
                        </tbody>           
                    </table>     
                </div>
            </div>
        </div>
    </div>
</div>
<script>
    function validateQty(event) {
        var key = window.event ? event.keyCode : event.which;

        if (event.keyCode == 8 || event.keyCode == 46
                || event.keyCode == 47 || event.keyCode == 39) {
            return true;
        }
        else if (key < 47 || key > 57) {
            return false;
        }
        else
            return true;
    }
    jQuery(document).ready(function() {
        jQuery('#show_to').datepicker({
            format: "dd/mm/yyyy"
        });
        jQuery('#show_from').datepicker({
            format: "dd/mm/yyyy"
        });

        jQuery("#deal_type").on("change", function() {
            jQuery("#history_form").submit();
        });

    });

    $(document).ready(function() {
        $('#example').DataTable({
            initComplete: function() {
                this.api().columns().every(function() {
                    var column = this;

                    var select = $('<select><option value=""></option></select>')
                            .appendTo($(column.footer()).empty())
                            .on('change', function() {
                                var val = $.fn.dataTable.util.escapeRegex(
                                        $(this).val()
                                        );

                                column
                                        .search(val ? '^' + val + '$' : '', true, false)
                                        .draw();
                            });

                    column.data().unique().sort().each(function(d, j) {
                        select.append('<option value="' + d + '">' + d + '</option>')
                    });
                });
            },
            "language": {
                "lengthMenu": "<?php echo $this->translate("Display"); ?> _MENU_ <?php echo $this->translate("entries"); ?>",
                                "zeroRecords": "<?php echo $this->translate("No data found"); ?>",
                                "info": "<?php echo $this->translate("Showing page"); ?> _PAGE_ of _PAGES_",
                                "infoFiltered": "(<?php echo $this->translate("filtered from"); ?> _MAX_ <?php echo $this->translate("total records"); ?>)",
                                "paginate": {
                                    "previous": "<?php echo $this->translate("Previous"); ?>",
                                    "next": "<?php echo $this->translate("Next"); ?>"
                                }
                            }
                        });

                        jQuery("#deal_type").on("change", function() {
                            jQuery("#history_form").submit();
                        });
                    });
</script>